{"uuid": "2bc9f92d-3417-43f0-a1dc-c837998d2085", "children": ["89e30135-2eb8-4d89-b255-328e090b1160", "959b6f8d-3971-47b0-aac4-2be422f8dd08", "ba4fa5d2-eca9-436f-9d9c-3ef2640b4ea7"], "befores": [{"name": "_xunit_setup_class_fixture_TestNewTaskPage", "status": "broken", "statusDetails": {"message": "playwright._impl._api_types.Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE at http://101.xx.xx.xx/dist/index.html#/login\n=========================== logs ===========================\nnavigating to \"http://101.xx.xx.xx/dist/index.html#/login\", waiting until \"load\"\n============================================================\n", "trace": "  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\python.py\", line 786, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\code\\pwpomdcs\\cases\\test_newTask.py\", line 18, in setup_class\n    args.login(self.page,\"zgy\",\"123456\")\n  File \"D:\\code\\pwpomdcs\\com\\args.py\", line 6, in login\n    lp.navigate()\n  File \"D:\\code\\pwpomdcs\\pages\\login_page.py\", line 13, in navigate\n    self.page.goto(self.host+\"/dist/index.html#/login\")\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9303, in goto\n    self._sync(\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 109, in _sync\n    return task.result()\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\playwright\\_impl\\_page.py\", line 473, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 138, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 482, in wrap_api_call\n    return await cb()\n  File \"C:\\Users\\86176\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 97, in inner_send\n    result = next(iter(done)).result()\n"}, "start": 1700199356193, "stop": 1700199366893}], "start": 1700199356193, "stop": 1700199367853}